# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a31e8b8871e72653638b464e4267c941b66f01753a359f9f880339e001abfe856e848516b150eca51566b1c971e9111772bd6a470896684a2eecb02c399b0bf

test:
  secret_key_base: 1321f5449999b6a95ed36461e71471ab21c211adcdbd9e04300798ab31da3a5d121a2a19e6b74a571490669c1a9ab8b3424149d257a15f630171490f0449fd24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
